[package]

name = "grpc"
version = "0.7.0-pre"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "../README.md"
keywords = ["grpc"]

[dependencies]
log             = "0.4"
# version 2.10 requires bytes 0.5
protobuf        = { version = ">=2.8.0, <2.10.0", features = ["with-bytes"] }
futures         = "0.1.*"
futures-cpupool = "0.1.*"
tokio-core      = "0.1.*"
tokio-io        = "0.1.*"
tokio-tls-api   = "0.1.*"
httpbis         = "~0.7"
tls-api         = "0.1"
tls-api-stub    = "0.1"
bytes           = "0.4.*"
base64          = "0.9"

[dev-dependencies]
env_logger      = "~0.5"

[lib]
doctest = false
